/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next/esm')['Aside']
    TBackTop: typeof import('tdesign-vue-next/esm')['BackTop']
    TButton: typeof import('tdesign-vue-next/esm')['Button']
    TComment: typeof import('tdesign-vue-next/esm')['Comment']
    TConfigProvider: typeof import('tdesign-vue-next/esm')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next/esm')['Content']
    TDivider: typeof import('tdesign-vue-next/esm')['Divider']
    THeader: typeof import('tdesign-vue-next/esm')['Header']
    THeadMenu: typeof import('tdesign-vue-next/esm')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next/esm')['Icon']
    TLayout: typeof import('tdesign-vue-next/esm')['Layout']
    TMenu: typeof import('tdesign-vue-next/esm')['Menu']
    TMenuItem: typeof import('tdesign-vue-next/esm')['MenuItem']
    TSpace: typeof import('tdesign-vue-next/esm')['Space']
    TSubmenu: typeof import('tdesign-vue-next/esm')['Submenu']
  }
}
